//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Consensus.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_CONSENSUS_DIALOG            102
#define IDR_MAINFRAME                   128
#define IDD_CEDT                        129
#define IDD_CRDC                        130
#define IDD_CONVENTION                  131
#define IDD_FINGERPRINT                 132
#define IDD_TEMPER                      133
#define IDD_SELLER_DIALOG               134
#define IDC_TAB1                        1000
#define IDC_RICHEDIT21                  1001
#define IDC_RICHEDIT22                  1002
#define IDC_BUTTON1                     1003
#define IDC_BUTTON2                     1004
#define IDC_RICHEDIT23                  1005
#define IDC_BUTTON13                    1005
#define IDC_TRAINING_CASE               1005
#define IDC_CHECK1                      1006
#define IDC_BUTTON14                    1006
#define IDC_START_TRAINING              1006
#define IDC_CHECK2                      1007
#define IDC_MODEL_PARAMETER             1007
#define IDC_CHECK3                      1008
#define IDC_CHECK4                      1009
#define IDC_LCWCC                       1009
#define IDC_CHECK5                      1010
#define IDC_SOFT_CONSTRAINT             1010
#define IDC_CHECK6                      1011
#define IDC_CHECK7                      1012
#define IDC_CHECK8                      1013
#define IDC_CHECK9                      1014
#define IDC_ENTITY_HEAD                 1014
#define IDC_CHECK10                     1015
#define IDC_INTERNET                    1015
#define IDC_CHECK11                     1016
#define IDC_CHECK12                     1017
#define IDC_CHECK13                     1018
#define IDC_CHECK14                     1019
#define IDC_CHECK15                     1020
#define IDC_CASE_CHECK                  1020
#define IDC_BUTTON15                    1021
#define IDC_XML_PARSE                   1021
#define IDC_BUTTON3                     1022
#define IDC_BUTTON16                    1022
#define IDC_CONVENTION_RESET            1022
#define IDC_BUTTON_RETURN               1022
#define IDC_RELATION_CASE               1022
#define IDC_CEDT_LOAD_MODELS            1022
#define IDC_PAD_BUTTON                  1022
#define IDC_BUTTON4                     1023
#define IDC_RADIO1                      1023
#define IDC_TYPE                        1023
#define IDC_BUTTON5                     1024
#define IDC_RADIO2                      1024
#define IDC_SUBTYPE                     1024
#define IDC_BUTTON6                     1025
#define IDC_CHECK17                     1026
#define IDC_CHECK18                     1027
#define IDC_CHECK19                     1028
#define IDC_CHECK20                     1029
#define IDC_BUTTON7                     1030
#define IDC_BUTTON8                     1031
#define IDC_VISUALIZATION               1031
#define IDC_BUTTON9                     1032
#define IDC_ENTITY_VIEW_BUTTON          1032
#define IDC_BUTTON10                    1033
#define IDC_FINGER_VIEWBUTTON           1033
#define IDC_CEDT_TESTING_MODEL          1033
#define IDC_BUTTON11                    1034
#define IDC_RELATION_VIEWBUTTON         1034
#define IDC_BUTTON12                    1035
#define IDC_TEMPER_VIEWBUTTON           1035
#define IDC_RADIO3                      1036
#define IDC_RADIO4                      1037
#define IDC_BUTTON17                    1038
#define IDC_INTEGRATION_VIEWBUTTON      1038
#define IDC_ENTITY_VIEW_BUTTON2         1039
#define IDC_GENERATE_NAMED_ENTITY_CASES 1040
#define IDC_ENTITY_VIEW_BUTTON3         1040
#define IDC_ACE_TRAIN_TEST              1040
#define IDC_GEN_TRAINING_CASES          1041
#define IDC_ENTITY_VIEW_BUTTON4         1041
#define IDC_GEN_TRAINING_CASES2         1042
#define IDC_START_NE_TRAINING           1042
#define IDC_ENTITY_VIEW_BUTTON5         1042
#define IDC_CEDT_ITERATE_TIME           1043
#define IDC_ENTITY_VIEW_BUTTON6         1043
#define IDC_CEDT_CANDIT_ITE             1043
#define IDC_RADIO_NE_DETECTION          1044
#define IDC_ENTITY_VIEW_BUTTON7         1044
#define IDC_CEDT_GEN_INFO               1045
#define IDC_ENTITY_VIEW_BUTTON8         1045
#define IDC_CEDT_WORDS_F                1046
#define IDC_ENTITY_VIEW_BUTTON9         1046
#define IDC_GEN_TRAINING_CASES3         1047
#define IDC_CEDT_TRAININT_MODELS        1047
#define IDC_CEDT_CHAR_CHECK             1048
#define IDC_CEDT_N_GRAM_CHECK           1049
#define IDC_RESET_CEDT                  1050
#define IDC_STELLER_RICHEDIT2           1051
#define IDC_BUTTON_CLEAR                1052
#define IDC_BUTTON_SAVE                 1053
#define IDC_CHECK_START                 1054
#define IDC_CHECK_END                   1055
#define IDC_BUTTON_ANALYSIZE_BOUNDARY_RET 1056
#define IDC_NE_RECOGNITION_RADIO        1057
#define IDC_BUTTON_SAVE_AS              1059
#define IDC_BUTTON_OPEN_HISTORY         1060
#define IDC_OPEN_RET_HISTORY            1061
#define IDC_ENTITY_SUBTYPE              1063
#define IDC_POSITIONAL_STRUCTURE        1064
#define IDC_OMNI_WORD                   1065
#define IDC_ALL_FEATURE                 1066
#define IDC_ICTCLAS                     1067
#define IDC_ALL_LEXICON                 1068
#define IDC_SEGMENTATION                1069
#define IDC_ITERATOR_TIME               1070
#define IDC_CRDC_STOP                   1071
#define IDC_GEN_ICTCLAS_LEXICON         1072
#define IDC_RDC_FOR_ENGLISH             1074
#define IDC_ENTITY_CLASS                1076
#define IDC_CEDT_HEAD                   1077
#define IDC_CEDT_EXTEND                 1078
#define IDC_CEDT_BOUND_ITE              1079
#define IDC_CEDT_N_GRAM                 1080
#define IDC_CEDT_SENT_INPUT             1081
#define IDC_CEDT_DOC_RECOG              1082
#define IDC_CEDT_SENT_DET               1083
#define IDC_CEDT_SENT_RECOG             1084
#define IDC_CEDT_SET_TRAININT_PATH      1085
#define IDC_CEDT_SET_TEST_PATH          1086
#define IDC_CEDT_FORBID_MODEL           1087
#define IDC_CEDT_AUTO_LOAD_MODEL        1088
#define IDC_CEDT_SET_RECOG_DOC          1089
#define IDC_CEDT_DOC_PATH               1090
#define IDC_CEDT_SENT_CLEAR             1091
#define IDC_CRDC_nCROSS                 1092
#define IDC_RICHEDIT24                  1093
#define IDC_RICHEDIT25                  1094
#define IDC_RICHEDIT26                  1095
#define IDC_CRDC_INPUT                  1095
#define IDC_CRDC_TRAININT               1096
#define IDC_CRDC_RECOGNITION            1097
#define IDC_CRDC_LOAD_MODEL             1098
#define IDC_STELLER_PAUSE               1099

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        135
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1100
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
