//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Consensus.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_CONSENSUS_DIALOG            102
#define IDR_MAINFRAME                   128
#define IDD_CEDT                        129
#define IDD_CRDC                        130
#define IDD_CONVENTION                  131
#define IDD_CDOC                        132
#define IDD_SELLER_DIALOG               134
#define IDR_CRDC_INPUT_MENU             136
#define IDD_ECOR                        138
#define IDR_241                         143
#define IDD_DOC_EVENT_REVIEWER          145
#define IDD_ANALYZER                    146
#define IDB_BITMAP1                     147
#define IDR_ANAL_ENABLE_BUTTON          148
#define IDC_TAB1                        1000
#define IDC_RICHEDIT21                  1001
#define IDC_RICHEDIT22                  1002
#define IDC_BUTTON1                     1003
#define IDC_BUTTON2                     1004
#define IDC_RICHEDIT23                  1005
#define IDC_BUTTON13                    1005
#define IDC_TRAINING_CASE               1005
#define IDC_BUTTON14                    1006
#define IDC_START_TRAINING              1006
#define IDC_CHECK1                      1007
#define IDC_MODEL_PARAMETER             1007
#define IDC_ANAL_PERSON                 1007
#define IDC_CHECK3                      1008
#define IDC_ANAL_ORG                    1008
#define IDC_CHECK4                      1009
#define IDC_LCWCC                       1009
#define IDC_ENET_FILTER_LOC             1009
#define IDC_CHECK5                      1010
#define IDC_POS_TAG                     1010
#define IDC_ENET_FILTER_ORG             1010
#define IDC_CHECK6                      1011
#define IDC_ENET_FILTER_PER_SOC         1011
#define IDC_CHECK7                      1012
#define IDC_ENET_FILTER_GEN_AFF         1012
#define IDC_CHECK8                      1013
#define IDC_ENET_FILTER_ORG_AFF         1013
#define IDC_CHECK9                      1014
#define IDC_ENTITY_HEAD                 1014
#define IDC_CHECK10                     1015
#define IDC_INTERNET                    1015
#define IDC_ENET_FILTER_PART_WHOLE      1015
#define IDC_CHECK11                     1016
#define IDC_CHECK12                     1017
#define IDC_CHECK13                     1018
#define IDC_CHECK14                     1019
#define IDC_CHECK15                     1020
#define IDC_CASE_CHECK                  1020
#define IDC_BUTTON15                    1021
#define IDC_XML_PARSE                   1021
#define IDC_BUTTON3                     1022
#define IDC_BUTTON16                    1022
#define IDC_CONVENTION_RESET            1022
#define IDC_BUTTON_RETURN               1022
#define IDC_RELATION_CASE               1022
#define IDC_CEDT_LOAD_MODELS            1022
#define IDC_PAD_BUTTON                  1022
#define IDC_BUTTON4                     1023
#define IDC_RADIO1                      1023
#define IDC_TYPE                        1023
#define IDC_BUTTON5                     1024
#define IDC_RADIO2                      1024
#define IDC_SUBTYPE                     1024
#define IDC_BUTTON6                     1025
#define IDC_CHECK17                     1026
#define IDC_CHECK18                     1027
#define IDC_CHECK19                     1028
#define IDC_CHECK20                     1029
#define IDC_BUTTON7                     1030
#define IDC_BUTTON8                     1031
#define IDC_VISUALIZATION               1031
#define IDC_BUTTON9                     1032
#define IDC_ENTITY_VIEW_BUTTON          1032
#define IDC_BUTTON10                    1033
#define IDC_FINGER_VIEWBUTTON           1033
#define IDC_CEDT_TESTING_MODEL          1033
#define IDC_BUTTON11                    1034
#define IDC_RELATION_VIEWBUTTON         1034
#define IDC_BUTTON12                    1035
#define IDC_TEMPER_VIEWBUTTON           1035
#define IDC_RADIO3                      1036
#define IDC_RADIO4                      1037
#define IDC_BUTTON17                    1038
#define IDC_INTEGRATION_VIEWBUTTON      1038
#define IDC_ENTITY_VIEW_BUTTON2         1039
#define IDC_GENERATE_NAMED_ENTITY_CASES 1040
#define IDC_ENTITY_VIEW_BUTTON3         1040
#define IDC_ACE_TRAIN_TEST              1040
#define IDC_GEN_TRAINING_CASES          1041
#define IDC_ENTITY_VIEW_BUTTON4         1041
#define IDC_GEN_TRAINING_CASES2         1042
#define IDC_START_NE_TRAINING           1042
#define IDC_ENTITY_VIEW_BUTTON5         1042
#define IDC_CEDT_ITERATE_TIME           1043
#define IDC_ENTITY_VIEW_BUTTON6         1043
#define IDC_CEDT_CANDIT_ITE             1043
#define IDC_RADIO_NE_DETECTION          1044
#define IDC_ENTITY_VIEW_BUTTON7         1044
#define IDC_CEDT_GEN_INFO               1045
#define IDC_ENTITY_VIEW_BUTTON8         1045
#define IDC_CEDT_WORDS_F                1046
#define IDC_ENTITY_VIEW_BUTTON9         1046
#define IDC_GEN_TRAINING_CASES3         1047
#define IDC_CEDT_TRAININT_MODELS        1047
#define IDC_CEDT_CHAR_CHECK             1048
#define IDC_CEDT_N_GRAM_CHECK           1049
#define IDC_RESET_CEDT                  1050
#define IDC_STELLER_RICHEDIT2           1051
#define IDC_BUTTON_CLEAR                1052
#define IDC_BUTTON_SAVE                 1053
#define IDC_CHECK_START                 1054
#define IDC_CHECK_END                   1055
#define IDC_BUTTON_ANALYSIZE_BOUNDARY_RET 1056
#define IDC_NE_RECOGNITION_RADIO        1057
#define IDC_BUTTON_SAVE_AS              1059
#define IDC_BUTTON_OPEN_HISTORY         1060
#define IDC_OPEN_RET_HISTORY            1061
#define IDC_ENTITY_SUBTYPE              1063
#define IDC_POSITIONAL_STRUCTURE        1064
#define IDC_OMNI_WORD                   1065
#define IDC_ALL_FEATURE                 1066
#define IDC_ICTCLAS                     1067
#define IDC_ALL_LEXICON                 1068
#define IDC_SEGMENTATION                1069
#define IDC_ITERATOR_TIME               1070
#define IDC_GEN_ICTCLAS_LEXICON         1072
#define IDC_ENTITY_CLASS                1076
#define IDC_CEDT_HEAD                   1077
#define IDC_CEDT_EXTEND                 1078
#define IDC_CEDT_BOUND_ITE              1079
#define IDC_CEDT_N_GRAM                 1080
#define IDC_CEDT_SENT_INPUT             1081
#define IDC_CEDT_DOC_RECOG              1082
#define IDC_CEDT_SENT_DET               1083
#define IDC_CEDT_SENT_RECOG             1084
#define IDC_CEDT_SET_TRAININT_PATH      1085
#define IDC_CEDT_SET_TEST_PATH          1086
#define IDC_CEDT_FORBID_MODEL           1087
#define IDC_CEDT_AUTO_LOAD_MODEL        1088
#define IDC_CEDT_SET_RECOG_DOC          1089
#define IDC_CEDT_DOC_PATH               1090
#define IDC_CEDT_SENT_CLEAR             1091
#define IDC_CRDC_nCROSS                 1092
#define IDC_RICHEDIT24                  1093
#define IDC_REDIT_CRDC_OUTPUT           1093
#define IDC_CDOC_TWORDS                 1093
#define IDC_RICHEDIT25                  1094
#define IDC_CDOC_NITERS                 1094
#define IDC_RICHEDIT26                  1095
#define IDC_CRDC_INPUT                  1095
#define IDC_CRDC_TRAININT               1096
#define IDC_CRDC_RECOGNITION            1097
#define IDC_CRDC_LOAD_MODEL             1098
#define IDC_STELLER_PAUSE               1099
#define IDC_REDIT_ARG1                  1100
#define IDC_REDIT_ARG2                  1101
#define IDC_CRDC_DEL                    1102
#define IDC_CRDC_RUN                    1103
#define IDC_ECOR_TRAIN_TEST             1104
#define IDC_ECOR_N_CROSS                1105
#define IDC_ECOR_STANFORD_PARSING       1106
#define IDC_RICHEDIT_ECOR_ITE           1107
#define IDC_ECOR_LOAD_CANDIT            1108
#define IDC_ECOR_UPDATE_CANDIT          1109
#define IDC_ECOR_PS_A_LOA               1110
#define IDC_CEOR_PS_UPDATE              1111
#define IDC_ECOR_PARTING                1112
#define IDC_CRDC_COLLECT_PAR            1112
#define IDC_ECOR_UPDATE_CANDIT2         1113
#define IDC_ECOR_SAVE_TESTED            1113
#define IDC_CRDC_OUTPUT_SVM             1113
#define IDC_CDOC_                       1114
#define IDC_CDOC_SPARSING               1114
#define IDC_CDOC_MATRIX                 1115
#define IDC_DOC_PARSE_ACE               1117
#define IDC_DOC_LCWCC                   1118
#define IDC_DOC_ACE_ENTITY              1119
#define IDC_DOC_ICTCLAS                 1120
#define IDC_CDOC_LDA_TRAINING           1121
#define IDC_CDOC_TOPICS                 1122
#define IDC_CDOC_ALPHA                  1123
#define IDC_CDOC_BETA                   1124
#define IDC_DOC_FILTERING_TERMS         1125
#define IDC_CDOC_HIGH_RATION            1126
#define IDC_CDOC_LOW_RATION             1127
#define IDC_CDOC_LOW_FREQ               1128
#define IDC_CDOC_DEGUG_DOC              1129
#define IDC_CDOC_DUBEG_NUM              1130
#define IDC_CDOC_ACTIVE_ACE             1131
#define IDC_CDOC_ACTIVE_GIGAWORD        1132
#define IDC_CDOC_DO_ALL                 1133
#define IDC_CDOC_CLUSTERING             1135
#define IDC_CDOC_ORGANIZING             1136
#define IDC_CDOC_HIERARCHIES            1137
#define IDC_CDOC_TIMESTEP               1138
#define IDC_CDOC_ACTIVE_ORG             1139
#define IDC_CDOC_BREAKPOINT             1140
#define IDC_CHECK2                      1141
#define IDC_DOC_EVENTS_BUTTEN           1146
#define IDC_ANAL_DEWER                  1147
#define IDC_DOC_EVENT_LIST              1148
#define IDC_ANAL_DEWER_RUN              1148
#define IDC_ANAL_LOAD_DOC               1149
#define IDC_VIEWER_DOC_FOLDER_SET       1150
#define IDC_VIEWER_NEXT_TIME            1150
#define IDC_VIEWER_FOLDER_PATH          1151
#define IDC_VIEWER_FRONT_TIME           1152
#define IDC_VIEWER_DOC_NUM              1153
#define IDC_VIEWER_EVENT_NUM            1154
#define IDC_VIEWER_SELE_EVENT           1155
#define IDC_VIEWER_OPEN_EN              1156
#define IDC_VIEWER_COLLECT_DOC_E        1156
#define IDC_ANAL_ENTITY_RUN             1157
#define IDC_VIEWER_NEXT_TIME2           1157
#define IDC_ANAL_ENTITY_RESULTS         1158
#define IDC_ANAL_ENTITY_VIEWER          1159
#define IDC_ANAL_REL_RUN                1160
#define IDC_ANAL_REL_RESULTS            1161
#define IDC_ANAL_REL_VIEWER             1162
#define IDC_ANAL_RESET                  1163
#define IDC_ANAL_RUN_ALL                1164
#define IDC_ANAL_PAUSE                  1165
#define IDC_ANAL_STOP                   1166
#define IDC_ANAL_VIEWER                 1167
#define IDC_ANAL_GEN_EN                 1168
#define IDC_ANAL_RESULTS                1169
#define IDC_ANAL_LOCATION               1170
#define IDC_ANAL_REL_TYPE               1171
#define IDC_ANAL_REL_SUBTYPE            1172
#define IDC_ANAL_PICTURE                1173
#define IDC_ANAL_EXAMPLE                1174
#define IDC_ENET_LOAD_INFO              1174
#define IDC_REVIER_PAGES                1175
#define IDC_REVIEW_NEXT                 1176
#define IDC_REVIEW_FRONT                1177
#define IDC_ANA_EVENT_NAME              1178
#define IDC_ANAL_KEY_WORDS              1179
#define IDC_ENET_SP_CHECK               1188
#define IDC_ENET_CENT_COMBO             1191
#define IDC_ENET_SPA1_COMBO             1192
#define IDC_ENET_SPA2_COMBO             1193
#define IDC_ENET_BOTTON_EDIT            1194
#define IDC_ENET_NE_WEIGHT              1195
#define IDC_ENET_REL_WEITHG             1196
#define IDC_ENET_MAX_VEX                1197
#define IDC_ENET_FILTER_PER             1198
#define IDC_ENET_FILTER_PHYS            1199
#define ID_ARG                          32772
#define ID_MANU_ARG                     32773
#define ID_MANU_ARG32774                32774
#define ID_MANU_ARG_1                   32775
#define ID_MANU_ARG_2                   32776

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        149
#define _APS_NEXT_COMMAND_VALUE         32777
#define _APS_NEXT_CONTROL_VALUE         1200
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
